package com.codingShuttle.projects.buildX.platform.service.impl;

import com.codingShuttle.projects.buildX.platform.llm.PromptUtils;
import com.codingShuttle.projects.buildX.platform.llm.advisers.FileTreeContextAdviser;
import com.codingShuttle.projects.buildX.platform.llm.tools.CodeGenerationTool;
import com.codingShuttle.projects.buildX.platform.security.AuthUtil;
import com.codingShuttle.projects.buildX.platform.service.AiGenerationService;
import com.codingShuttle.projects.buildX.platform.service.ProjectFileService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.scheduler.Schedulers;

//import javax.swing.*;
import java.time.Duration;
import java.util.Map;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
@RequiredArgsConstructor
@Slf4j
public class AiGenerationServiceImpl implements AiGenerationService {

    private final ChatClient chatClient;
    private final AuthUtil authUtil;
    private final ProjectFileService projectFileService;
    private final FileTreeContextAdviser fileTreeContextAdviser;

    private static final Pattern FILE_TAG_PATTERN =
            Pattern.compile("<file path=\"([^\\\"]+)\">(.*?)</file>", Pattern.DOTALL);

    @Override
//    @PreAuthorize("@security.canEditProject(#projectId)")
    public Flux<String> streamResponse(String userMessage, Long projectId) {
        Long userId = authUtil.getCurrentUserId();
        createChatSessionIfNotExists(projectId, userId);

        Map<String, Object> advisorParams = Map.of(
                "userId", userId,
                "projectId", projectId
        );

        StringBuilder fullResponseBuffer = new StringBuilder();//this will append the string message generated by gpt

        CodeGenerationTool codeGenerationTool = new CodeGenerationTool(projectFileService, projectId);
        return chatClient.prompt()
                .system(PromptUtils.CODE_GENERATION_SYSTEM_PROMPT)
                .user(userMessage)
                .tools(codeGenerationTool)
                .advisors(advisorSpec -> {
                    advisorSpec.params(advisorParams);
                    advisorSpec.advisors(fileTreeContextAdviser);
                })
                .stream()
                .chatResponse()
                .delayElements(Duration.ofMillis(200))
                .doOnNext(response -> {
                    String content = response.getResult().getOutput().getText();
                    if (content != null) {
                        fullResponseBuffer.append(content);
                    }
                })
                .doOnComplete(()->{
                    Schedulers.boundedElastic().schedule(()->{ // this is multithreading, Asysnc using this Schedulers just because
                        parseAndSaveFiles(fullResponseBuffer.toString(), projectId);//we are using Flux for string streaming otherwise we could have used ExecutorService or any other multithreading methods
                    });
                })
                .doOnError(error -> log.error("Error during streaming for projectId {}", projectId, error))
                // Use handle to safely drop null responses (tool calls) without crashing Reactor
                .handle((response, sink) -> {
                    String text = response.getResult().getOutput().getText();
                    if (text != null) {
                        sink.next(text);
                    }
                });
    }

    private void parseAndSaveFiles(String fullResponse, Long projectId) {

        Matcher matcher = FILE_TAG_PATTERN.matcher(fullResponse);
        while(matcher.find()){
            String filePath = matcher.group(1);
            String fileContent = matcher.group(2).trim();

            projectFileService.saveFile(projectId, filePath, fileContent);
        }
    }

    private void createChatSessionIfNotExists(Long projectId, Long userId) {
    }
}
