package com.codingShuttle.projects.buildX.platform.service.impl;

import com.codingShuttle.projects.buildX.platform.entity.*;
import com.codingShuttle.projects.buildX.platform.enums.ChatEventType;
import com.codingShuttle.projects.buildX.platform.enums.MessageRole;
import com.codingShuttle.projects.buildX.platform.error.ResourceNotFoundException;
import com.codingShuttle.projects.buildX.platform.llm.LlmResponseParser;
import com.codingShuttle.projects.buildX.platform.llm.PromptUtils;
import com.codingShuttle.projects.buildX.platform.llm.advisers.FileTreeContextAdviser;
import com.codingShuttle.projects.buildX.platform.llm.tools.CodeGenerationTool;
import com.codingShuttle.projects.buildX.platform.repository.*;
import com.codingShuttle.projects.buildX.platform.security.AuthUtil;
import com.codingShuttle.projects.buildX.platform.service.AiGenerationService;
import com.codingShuttle.projects.buildX.platform.service.ProjectFileService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.scheduler.Schedulers;

import java.util.Set;
import java.util.concurrent.atomic.AtomicLong;

//import javax.swing.*;
import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicReference;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
@RequiredArgsConstructor
@Slf4j
public class AiGenerationServiceImpl implements AiGenerationService {

    private final ChatClient chatClient;
    private final AuthUtil authUtil;
    private final ProjectFileService projectFileService;
    private final FileTreeContextAdviser fileTreeContextAdviser;
    private final LlmResponseParser llmResponseParser;
    private final ChatSessionRepository chatSessionRepository;
    private final ProjectRepository projectRepository;
    private final UserRepository userRepository;
    private final ChatMessageRepository chatMessageRepository;
    private final ChatEventRepository chatEventRepository;


    private static final Pattern FILE_TAG_PATTERN =
            Pattern.compile("<file path=\"([^\\\"]+)\">(.*?)</file>", Pattern.DOTALL);

    @Override
    public Flux<String> streamResponse(String userMessage, Long projectId) {
        Long userId = authUtil.getCurrentUserId();
        ChatSession chatSession = createChatSessionIfNotExists(projectId, userId);

        Map<String, Object> advisorParams = Map.of(
                "userId", userId,
                "projectId", projectId
        );

        StringBuilder fullResponseBuffer = new StringBuilder();//this will append the string message generated by gpt
        java.util.Set<String> savedFiles = new java.util.HashSet<>();

        AtomicReference<Long> startTime = new AtomicReference<>(System.currentTimeMillis());
        AtomicReference<Long> endTime = new AtomicReference<>(0L);

        CodeGenerationTool codeGenerationTool = new CodeGenerationTool(projectFileService, projectId);
        String fileTree = projectFileService.getFileTree(projectId).toString();
        return chatClient.prompt()
                .system(PromptUtils.codeGenerationSystemPrompt(fileTree))
                .user(userMessage)
                .tools(codeGenerationTool)
                .advisors(advisorSpec -> {
                    advisorSpec.params(advisorParams);
                    advisorSpec.advisors(fileTreeContextAdviser);
                })
                .stream()
                .chatResponse()
                .delayElements(Duration.ofMillis(200))
                .doOnNext(response -> {
                    if (response == null || response.getResult() == null || response.getResult().getOutput() == null) {
                        return;
                    }
                    String content = response.getResult().getOutput().getText();
                    if (content != null && !content.isEmpty() && endTime.get() == 0) {
                        endTime.set(System.currentTimeMillis());
                    }
                    fullResponseBuffer.append(content);
                    Matcher matcher = FILE_TAG_PATTERN.matcher(fullResponseBuffer.toString());
                    while (matcher.find()) {
                        String filePath = matcher.group(1);
                        String fileContent = matcher.group(2);
                        if (!savedFiles.contains(filePath)) {
                            savedFiles.add(filePath);
                            Schedulers.boundedElastic().schedule(() -> {
                                try {
                                    projectFileService.saveFile(projectId, filePath, fileContent);
                                    log.info("Saved file on the fly: {}", filePath);
                                } catch (Exception e) {
                                    log.error("Failed to save file on the fly: {}", filePath, e);
                                }
                            });
                        }
                    }
                })
                .doOnComplete(()->{
                    Schedulers.boundedElastic().schedule(()->{ // this is multithreading, Asysnc using thiss Schedulers just because
//                        parseAndSaveFiles(fullResponseBuffer.toString(), projectId);//we are using Flux for string streaming otherwise we could have used ExecutorService or any other multithreading methods
                        long duration = (endTime.get() - startTime.get()) / 1000;
                        finalizeChats(userMessage, chatSession, fullResponseBuffer.toString(), duration);
                    });
                })
                .doOnError(error -> log.error("Error during streaming for projectId {}", projectId, error))
                // Use handle to safely drop null responses (tool calls) without crashing Reactor
                .handle((response, sink) -> {
                    if (response != null && response.getResult() != null && response.getResult().getOutput() != null) {
                        String text = response.getResult().getOutput().getText();
                        if (text != null) {
                            sink.next(text);
                        }
                    }
                });
    }

    private void finalizeChats(String userMessage, ChatSession chatSession, String fullText, Long duration){
        //save the user message
        Long projectId = chatSession.getProject().getId();
        chatMessageRepository.save(
                ChatMessage.builder()
                        .chatSession(chatSession)
                        .role(MessageRole.USER)
                        .content(userMessage)
                        .build()
        );

        ChatMessage assistantChatMessage = ChatMessage.builder()
                .role(MessageRole.ASSISTANT)
                .chatSession(chatSession)
                .content(fullText)
                .build();

        assistantChatMessage = chatMessageRepository.save(assistantChatMessage);

        List<ChatEvent> chatEventList = llmResponseParser.parseChatEvents(fullText,assistantChatMessage);

        chatEventList.addFirst(ChatEvent.builder()
                        .type(ChatEventType.THOUGHT)
                        .chatMessage(assistantChatMessage)
                        .content("Thought for" + duration +"s")
                        .sequenceOrder(0)
                .build());
        Map<String, ChatEvent> uniqueFileEdits = new java.util.LinkedHashMap<>();
        chatEventList.stream()
                .filter(e -> e.getType() == ChatEventType.FILE_EDIT)
                .forEach(e -> uniqueFileEdits.put(e.getFilePath(), e));
        uniqueFileEdits.values().forEach(e ->
                projectFileService.saveFile(projectId, e.getFilePath(), e.getContent())
        );

        chatEventRepository.saveAll(chatEventList);
    }

    private ChatSession createChatSessionIfNotExists(Long projectId, Long userId) {

        ChatSessionId chatSessionId = new ChatSessionId(projectId, userId);
        ChatSession chatSession = chatSessionRepository.findById(chatSessionId).orElse(null);

        if(chatSession == null){
            Project project = projectRepository.findById(projectId).orElseThrow(
                    ()-> new ResourceNotFoundException("Project", projectId.toString()));

            User user = userRepository.findById(userId).orElseThrow(
                    ()-> new ResourceNotFoundException("UserId", userId.toString()));

            chatSession = ChatSession.builder()
                    .id(chatSessionId)
                    .project(project)
                    .user(user)
                    .build();

            chatSession = chatSessionRepository.save(chatSession);

        }

        return chatSession;
    }
}
